language: python
python:
- 3.6

services:
  - docker

install:
- pip install -r requirements.txt -r dev-requirements.txt
- docker build --tag niccokunzmann/freifunk-website-proxy .
- export CONTAINER_NAME=test-container-travis

script:
- pytest
- "docker run -p 9000:80 -e DOMAIN=localhost:9000 -d --name $CONTAINER_NAME --rm niccokunzmann/freifunk-website-proxy && sleep 1"
- "docker ps | grep -q -F $CONTAINER_NAME"
