# Build the docker image and push it to the docker image registry
#
# From https://github.com/marketplace/actions/build-and-push-docker-images
#

name: build-docker-image

on:
  # run on new commits on the branch
  # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
#  push:
#    branches:
#      - master
#  schedule:
  # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
  # see https://crontab.guru/every-month
#  - cron: '0 0 1 * *'
  # only run when the workflow for the tests completed
  # see https://stackoverflow.com/a/64733705/1320237
  workflow_run:
    workflows:
      - tests
    branches:
      - master
    types: 
      - completed

jobs:
  docker:
    # only run if the tests succeed
    # see https://stackoverflow.com/a/68078768/1320237
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: niccokunzmann/dynamic-website-reverse-proxy:latest
